### ISSUE TITLE
/look in pocket just showing /look

### ISSUE THREAD

**Issue by Hazado** [H-uru/Plasma#1492]
the Easter egg command "/look in pocket" just shows /look instead

**Comment by ZarothYe** [comment]
I think I see from the code why this is happening, give me a few days to get it fixed.

**Comment by Mirphak** [comment]
In xKIChat.py, the commands beginning by "/" are splited, so "/look in pocket" is understand as /look with parameters.
![image](https://github.com/H-uru/Plasma/assets/1476226/6e01b3cf-cdee-44b6-8daa-89ca2a353eec)

**Comment by ZarothYe** [comment]
> In xKIChat.py, the commands beginning by "/" are splited, so "/look in pocket" is understand as /look with parameters. 

That's a good note, but `/look in pocket` is part of the `kEasterEgg` constant commands handled on 928 prior to the emote and `/me` handling that you're showing. I need to do more testing to be 100% sure, but I believe this is happening because in the iteration of checking well-known commands, it checks if the message starts with `/look` first instead of the more-specific `/look in pocket`. It may be as easy as re-ordering the commands in `xKIConstants.py` so that the `/look in pocket` command match is checked first. I'll try to submit something this weekend after testing locally.

**Comment by Mirphak** [comment]
You are right.
I'm not sure how items in dictionary are read, maybe putting  "/look in pocket" before "/look" will work? We may have to sort the dictionary?

**Comment by Mirphak** [comment]
With
for command, function in reversed(commands.items()):
I have that:
![image](https://github.com/H-uru/Plasma/assets/1476226/97b64ec8-e074-44ad-bff0-56a60221977f)
