### ISSUE TITLE
3dsMax 2020 Python list empty with release version

### ISSUE THREAD

**Issue by Filtik** [H-uru/Plasma#1616]
Hi, sorry that I have to create another issue.
In 3dsMax 2020, the Python list is empty with the release version.
It is full with the debug version.
There was also an error when taking the picture, but I don't think it's that urgent.
I'm using Windows 11 if that helps.

Release version:
<img width="238" alt="Py1" src="https://github.com/user-attachments/assets/d4c18146-c2d2-4efa-9a91-837047e9ec75">

Debug version:
<img width="236" alt="Py2" src="https://github.com/user-attachments/assets/bc455152-119d-4064-a10c-06c57aac5f49">

Error by picture make:
<img width="312" alt="2024-10-06 06_18_38-Microsoft Visual C++ Runtime Library" src="https://github.com/user-attachments/assets/614257a2-8459-4f06-a9a2-89df28e6038c">

**Comment by dpogue** [comment]
We only know about and can fix issues if people report them, so thank you for reporting this!

My first thought is to try to reproduce this on a different version of 3DS Max to confirm if it's a Max issue (or Max + MSVCRT combination issue) or a problem with loading the Python files entirely.

Out of curiosity, your release build is still an Internal client, right?

**Comment by Filtik** [comment]
I only tried it with the external release version.
I have now tested the internal release version and the list is full again.

**Comment by dpogue** [comment]
My guess is that because the external release doesn't allow loading Python files from the filesystem, it ends up returning an empty list.

Cyan probably never intended the Max plugin to be built as part of an external release, maybe we should prevent that combination of options in CMake to avoid people getting into this kind of situation with a Max plugin that doesn't actually work properly?
