### ISSUE TITLE
PhysX 3.4 is now open source

### ISSUE THREAD

**Issue by bertvandepoel** [H-uru/Plasma#578]
Not sure if this is relevant, since the version used in Plasma is so much lower. But NVIDIA has opensourced some of their PhysX code: https://github.com/NVIDIAGameWorks/PhysX-3.4 https://www.linuxnewssite.com/nvidia-released-physx-source-code-under-bsd-3-license-03122018974.html

Didn't really know how to communicate it, so I just made this issue.

**Comment by Deledrius** [comment]
Thanks for bringing this to our attention!  I hadn't heard about this development.

**Comment by QORTEC** [comment]
NVIDIA also released PhysX 4 SDK on December 18, 2018
- https://github.com/NVIDIAGameWorks/PhysX

According to **README.md** Plasma currently requires PhysX 2.6.4. Since NVIDIA has open sourced PhysX SDK 3.4 and 4, Plasma will likely require updating its PhysX code to take advantage of this.
How would the open sourcing of PhysX effect issues #4 and #34?

**Comment by QORTEC** [comment]
@bertvandepoel, I've also been watching the project for some time now and I agree with your observations regarding the project. However according to my understanding (which is limited) PhysX is compatible with Linux and there are build instructions for Linux on their GitHub.

Due to my limited knowledge I really don't know how feasible it is to adopt PhysX 3.5 or 4 vs Bullet. 
- On the one hand the project already uses PhysX code, however the code will need "updating" and I don't know how good the Linux support is (only that its listed as supported).
- On the other hand if the code would require extensive rewriting to update to a newer version of PhysX then the project may prefer to just continue porting to Bullet.

**Comment by zrax** [comment]
Part of the problem here is the cooked PhysX data stored in the .prp files, which we can't modify.  If my memory serves correctly (it often doesn't), this cooked data is not compatible with newer versions of PhysX, which has always been the biggest thing holding us back from updating.

**Comment by Deledrius** [comment]
> 
> 
> Part of the problem here is the cooked PhysX data stored in the .prp files, which we can't modify. 
Now that we can modify these, is it possible to uncook the physics data?  If so, should we do an update to the files that replaces the cooked with the uncooked allowing us to finally update?

**Comment by jamie-marchant** [comment]
Upgrading the PhysX engine will take a lot of testing, you guys sure this is a priority?

**Comment by Deledrius** [comment]
An issue open for eight years is hardly one I would consider a "priority", but as time passes being tied to a legacy version that is unsupported (and is 32-bit only) becomes an increasingly bigger problem.

**Comment by Hoikas** [comment]
Uncooking the data hasn't been an issue for years--there's a functioning implementation of this in libHSPlasma. The way I see it we can proceed in two ways:
1) Bring the uncooker over to Plasma OR
2) Uncook the PRPs offline and store them in our fancy, yet to be unleashed git-lfs.

**Comment by Hoikas** [comment]
Further discussion on this topic will proceed in #4 . Closing.
